export const CONTRACT_IDS = {
  // gitleaks:allow
  leafToken: "CDSK3UIEDWWLECIJ4IKEGSAK55IRPNNYOBSZ5QN4ZMOX3DL5SBKUYGPB",
  // gitleaks:allow
  sbtCompany: "CACWQXW5HTNUQBNCWAU62HWQCSBZO6FI2CISPHBMKDAF4NFWNYC35WOK",
  // gitleaks:allow
  masterChief: "CB5ZWH43V7BLLTFYLOYJCFRBQBKQWIPTRJMS4HEFJQX5SHYZEM2V5K3C",
  // gitleaks:allow
  sbtGuardian: "CATUQHSIINJTJGIMSROVY47M2IJI2HDTQ2COXGI43Z4UNXQQXIW7WYEB",
  // gitleaks:allow
  mythosVault: "CC3E5J47FPV7HZKSX3XE2Z6Y6X7VFC36HUYHGTC4NP3HMCOESPG7JP55",
  // gitleaks:allow
  journeyOrchestrator: "CDYBW7E33UT73BFVE73K6CWRCWK33O7DHCMZC6Z4HU2BX635ONPD7T6D"
};

export const NETWORK_CONFIG = {
  network: "testnet",
  rpcUrl: "https://soroban-testnet.stellar.org:443"
};

export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";