'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es' | 'zh' | 'ja' | 'de' | 'fr';

type Translations = Record<Language, Record<string, string>>;

const translations: Translations = {
    pt: {
        b2b_title: 'Onboarding B2B',
        b2b_desc: 'Provisione seu Ledger de Auditoria ESG na rede Stellar.',
        section_registry: 'Registro Institucional',
        label_nature: 'Natureza do Negócio',
        opt_pequena: 'Pequena Empresa (Comércio Local)',
        opt_industria: 'Indústria (Transformação, Manufatura)',
        opt_servicos: 'Serviços (Consultoria, Agência)',
        opt_servicos_digitais: 'Serviços Digitais (SaaS, Plataformas)',
        opt_empreendedor: 'Empreendedor Digital (Influencer, Infoprodutos)',
        label_name: 'Razão Social / Nome Artístico',
        label_doc: 'CNPJ ou CPF (Comercial)',
        label_email: 'Email de Contato',
        label_phone: 'Telefone / WhatsApp',
        btn_generate: 'Gerar Identidade Criptográfica',
        provisioning: 'Provisionando...',
        prov_desc: 'Registrando SBT e lastro na rede Stellar',
        success_badge: '✓ Conta Provisionada',
        wallet_label: 'Carteira Stellar',
        status_sbt: 'SBT Empresa ✓',
        status_lastro: 'Lastro 10 Mudas ✓',
        infra_label: 'Infraestrutura: Etherfuse Direct',
        infra_desc: 'Capital via Pix/Ted convertido em lastro regulado no cofre.',
        btn_fiat: 'Liquidar Aporte Fiduciário',
        nav_field: 'Field',
        nav_assets: 'Assets',
        nav_impact: 'Impact',
        nav_vault: 'Vault',
        dash_title: 'Dashboard ESG',
        overview: 'Portfolio Overview',
        carbon_seq: 'Carbono Seq.',
        trees: 'Árvores Ativas',
        yield: 'C-Cred Yield',
        rwa_title: 'RWA Collateral',
        ods_title: 'Metas ODS',
        verified_ok: 'AUDITOR_VERIFIED — Conta verificada pelo Oráculo Vereda',
        verified_pend: 'AGUARDANDO_AUDITORIA — Verificação pendente',
        tab_login: 'Login',
        tab_onboarding: 'Onboarding',
        tab_profile: 'Perfil & RWA',
        tab_missions: 'Missões',
        profile_title: 'Perfil Corporativo',
        btn_buy_trees: 'Comprar Árvores (RWA)',
        mission_title: 'Campanhas & Missões',
        leafs_avail: 'LEAFs Disponíveis',
        locked_missions: 'Missões Bloqueadas',
        locked_desc: 'Compre árvores RWA no seu Perfil para injetar liquidez no protocolo, desbloquear tokens LEAF e criar campanhas de engajamento.',
        create_mission: 'Criar Nova Missão',
        miss_name: 'Nome da Campanha (Ex: Compre 1 Café, Ganhe 1 Árvore)',
        miss_desc: 'Regras ou Objetivo da Campanha',
        miss_reward: 'Recompensa por Cliente (LEAFs)',
        btn_launch: 'Lançar Campanha',
        buy_sim_loading: 'Aguardando Liquidação RWA...',
        login_title: 'Login Institucional',
        login_desc: 'Acesse seu painel corporativo na rede Stellar.',
        login_doc: 'Email Comercial ou CNPJ',
        login_pwd: 'Senha',
        btn_login: 'Entrar na Conta',
        btn_freighter: 'Conectar Freighter (Web3)',
        login_sim_msg: 'Autenticando e obtendo chaves na Stellar...',
    },
    en: {
        b2b_title: 'B2B Onboarding',
        b2b_desc: 'Provision your ESG Audit Ledger on the Stellar network.',
        section_registry: 'Institutional Registry',
        label_nature: 'Business Nature',
        opt_pequena: 'Small Business (Local Retail)',
        opt_industria: 'Industry (Manufacturing)',
        opt_servicos: 'Services (Consulting, Agency)',
        opt_servicos_digitais: 'Digital Services (SaaS, Platforms)',
        opt_empreendedor: 'Digital Entrepreneur (Influencer, Info-products)',
        label_name: 'Company Name / Stage Name',
        label_doc: 'Company ID / Tax ID',
        label_email: 'Contact Email',
        label_phone: 'Phone Number',
        btn_generate: 'Generate Cryptographic Identity',
        provisioning: 'Provisioning...',
        prov_desc: 'Registering SBT and collateral on Stellar',
        success_badge: '✓ Account Provisioned',
        wallet_label: 'Stellar Wallet',
        status_sbt: 'Company SBT ✓',
        status_lastro: '10 Seedlings Collateral ✓',
        infra_label: 'Infrastructure: Etherfuse Direct',
        infra_desc: 'Fiat capital converted into regulated vault collateral.',
        btn_fiat: 'Settle Fiat Contribution',
        nav_field: 'Field',
        nav_assets: 'Assets',
        nav_impact: 'Impact',
        nav_vault: 'Vault',
        dash_title: 'ESG Dashboard',
        overview: 'Portfolio Overview',
        carbon_seq: 'Carbon Seq.',
        trees: 'Active Trees',
        yield: 'C-Cred Yield',
        rwa_title: 'RWA Collateral',
        ods_title: 'SDG Goals',
        verified_ok: 'AUDITOR_VERIFIED — Verified by Vereda Oracle',
        verified_pend: 'PENDING_AUDIT — Verification pending',
        tab_login: 'Login',
        tab_onboarding: 'Onboarding',
        tab_profile: 'Profile & RWA',
        tab_missions: 'Missions',
        profile_title: 'Corporate Profile',
        btn_buy_trees: 'Buy Trees (RWA)',
        mission_title: 'Campaigns & Missions',
        leafs_avail: 'Available LEAFs',
        locked_missions: 'Locked Missions',
        locked_desc: 'Buy RWA trees in your Profile to inject liquidity into the protocol, unlock LEAF tokens and create engagement campaigns.',
        create_mission: 'Create New Mission',
        miss_name: 'Campaign Name (e.g. Buy 1 Coffee, Get 1 Tree)',
        miss_desc: 'Rules or Campaign Objective',
        miss_reward: 'Reward per Customer (LEAFs)',
        btn_launch: 'Launch Campaign',
        buy_sim_loading: 'Awaiting RWA Settlement...',
        login_title: 'Institutional Login',
        login_desc: 'Access your corporate dashboard on the Stellar network.',
        login_doc: 'Work Email or Company ID',
        login_pwd: 'Password',
        btn_login: 'Sign In',
        btn_freighter: 'Connect Freighter (Web3)',
        login_sim_msg: 'Authenticating and fetching Stellar keys...',
    },
    es: {
        b2b_title: 'Onboarding B2B',
        b2b_desc: 'Aprovisione su Ledger de Auditoría ESG en Stellar.',
        section_registry: 'Registro Institucional',
        label_nature: 'Naturaleza del Negocio',
        opt_pequena: 'Pequeña Empresa (Comercio Local)',
        opt_industria: 'Industria (Manufactura)',
        opt_servicos: 'Servicios (Consultoría, Agencia)',
        opt_servicos_digitais: 'Servicios Digitales (SaaS)',
        opt_empreendedor: 'Emprendedor Digital (Influencer)',
        label_name: 'Razón Social / Nombre',
        label_doc: 'ID de Empresa / RFC',
        label_email: 'Correo Electrónico',
        label_phone: 'Teléfono',
        btn_generate: 'Generar Identidad Criptográfica',
        provisioning: 'Aprovisionando...',
        prov_desc: 'Registrando SBT y respaldo en Stellar',
        success_badge: '✓ Cuenta Aprovisionada',
        wallet_label: 'Billetera Stellar',
        status_sbt: 'SBT Empresa ✓',
        status_lastro: 'Respaldo 10 Plántulas ✓',
        infra_label: 'Infraestructura: Etherfuse Direct',
        infra_desc: 'Capital fiduciario convertido en respaldo regulado.',
        btn_fiat: 'Liquidar Aporte Fiduciario',
        nav_field: 'Campo',
        nav_assets: 'Activos',
        nav_impact: 'Impacto',
        nav_vault: 'Bóveda',
        dash_title: 'Tablero ESG',
        overview: 'Visión General',
        carbon_seq: 'Carbono Sec.',
        trees: 'Árboles Activos',
        yield: 'C-Cred Yield',
        rwa_title: 'Colateral RWA',
        ods_title: 'Metas ODS',
        verified_ok: 'AUDITOR_VERIFIED — Verificado por el Oráculo Vereda',
        verified_pend: 'PENDING_AUDIT — Verificación pendiente',
        tab_login: 'Ingreso',
        tab_onboarding: 'Onboarding',
        tab_profile: 'Perfil y RWA',
        tab_missions: 'Misiones',
        profile_title: 'Perfil Corporativo',
        btn_buy_trees: 'Comprar Árboles (RWA)',
        mission_title: 'Campañas y Misiones',
        leafs_avail: 'LEAFs Disponibles',
        locked_missions: 'Misiones Bloqueadas',
        locked_desc: 'Compre árboles RWA en su Perfil para inyectar liquidez al protocolo, desbloquear tokens LEAF y crear campañas de participación.',
        create_mission: 'Crear Nueva Misión',
        miss_name: 'Nombre de Campaña (Ej: Compra 1 Café, Gana 1 Árbol)',
        miss_desc: 'Reglas u Objetivo',
        miss_reward: 'Recompensa por Cliente (LEAFs)',
        btn_launch: 'Lanzar Campaña',
        buy_sim_loading: 'Esperando Liquidación RWA...',
        login_title: 'Ingreso Institucional',
        login_desc: 'Acceda a su tablero corporativo en Stellar.',
        login_doc: 'Email Comercial o ID',
        login_pwd: 'Contraseña',
        btn_login: 'Iniciar Sesión',
        btn_freighter: 'Conectar Freighter (Web3)',
        login_sim_msg: 'Autenticando y obteniendo llaves en Stellar...',
    },
    fr: {
        b2b_title: 'Onboarding B2B',
        b2b_desc: 'Provisionnez votre registre audit ESG sur Stellar.',
        section_registry: 'Registre Institutionnel',
        label_nature: 'Nature de l’entreprise',
        opt_pequena: 'Petite Entreprise (Commerce local)',
        opt_industria: 'Industrie (Fabrication)',
        opt_servicos: 'Services (Consulting, Agence)',
        opt_servicos_digitais: 'Services Numériques (SaaS)',
        opt_empreendedor: 'Entrepreneur Numérique (Influenceur)',
        label_name: 'Raison Sociale / Nom',
        label_doc: 'Numéro d’entreprise (SIRET)',
        label_email: 'Email de Contact',
        label_phone: 'Téléphone',
        btn_generate: 'Générer une Identité Cryptographique',
        provisioning: 'Provisionnement...',
        prov_desc: 'Enregistrement du SBT et garantie sur Stellar',
        success_badge: '✓ Compte Provisionné',
        wallet_label: 'Portefeuille Stellar',
        status_sbt: 'SBT Entreprise ✓',
        status_lastro: 'Garantie 10 Arbres ✓',
        infra_label: 'Infrastructure : Etherfuse Direct',
        infra_desc: 'Capital fiduciaire converti en garantie régulée.',
        btn_fiat: 'Régler la Contribution Fiduciaire',
        nav_field: 'Terrain',
        nav_assets: 'Actifs',
        nav_impact: 'Impact',
        nav_vault: 'Coffre',
        dash_title: 'Tableau de bord ESG',
        overview: 'Aperçu du Portfolio',
        carbon_seq: 'Carbone Séc.',
        trees: 'Arbres Actifs',
        yield: 'Rendement C-Cred',
        rwa_title: 'Garantie RWA',
        ods_title: 'Objectifs ODD',
        verified_ok: 'AUDITOR_VERIFIED — Vérifié par l’Oracle Vereda',
        verified_pend: 'PENDING_AUDIT — Vérification en attente',
        tab_login: 'Connexion',
        tab_onboarding: 'Intégration',
        tab_profile: 'Profil et RWA',
        tab_missions: 'Missions',
        profile_title: 'Profil d’Entreprise',
        btn_buy_trees: 'Acheter des Arbres (RWA)',
        mission_title: 'Campagnes et Missions',
        leafs_avail: 'LEAFs Disponibles',
        locked_missions: 'Missions Verrouillées',
        locked_desc: 'Achetez des arbres RWA dans votre Profil pour injecter des liquidités, débloquer des tokens LEAF et créer des campagnes.',
        create_mission: 'Créer une Nouvelle Mission',
        miss_name: 'Nom de la Campagne',
        miss_desc: 'Règles ou Objectif',
        miss_reward: 'Récompense (LEAFs)',
        btn_launch: 'Lancer la Campagne',
        buy_sim_loading: 'En attente du règlement RWA...',
        login_title: 'Connexion Institutionnelle',
        login_desc: 'Accédez à votre tableau de bord sur Stellar.',
        login_doc: 'Email ou SIRET',
        login_pwd: 'Mot de passe',
        btn_login: 'Se connecter',
        btn_freighter: 'Connecter Freighter (Web3)',
        login_sim_msg: 'Authentification sur Stellar...',
    },
    de: {
        b2b_title: 'B2B-Onboarding',
        b2b_desc: 'Stellen Sie Ihr ESG-Audit-Ledger auf Stellar bereit.',
        section_registry: 'Institutionelles Register',
        label_nature: 'Art des Geschäfts',
        opt_pequena: 'Kleinunternehmen (Lokaler Handel)',
        opt_industria: 'Industrie (Herstellung)',
        opt_servicos: 'Dienstleistungen (Beratung)',
        opt_servicos_digitais: 'Digitale Dienste (SaaS)',
        opt_empreendedor: 'Digitaler Unternehmer (Influencer)',
        label_name: 'Firmenname / Künstlername',
        label_doc: 'Unternehmens-ID / Steuernummer',
        label_email: 'Kontakt E-Mail',
        label_phone: 'Telefonnummer',
        btn_generate: 'Kryptografische Identität Generieren',
        provisioning: 'Bereitstellung...',
        prov_desc: 'Registrierung von SBT und Sicherheit auf Stellar',
        success_badge: '✓ Konto Bereitgestellt',
        wallet_label: 'Stellar-Wallet',
        status_sbt: 'SBT Unternehmen ✓',
        status_lastro: 'Sicherheit 10 Setzlinge ✓',
        infra_label: 'Infrastruktur: Etherfuse Direct',
        infra_desc: 'Fiat-Kapital in regulierte Tresorsicherheit umgewandelt.',
        btn_fiat: 'Fiat-Beitrag Begleichen',
        nav_field: 'Feld',
        nav_assets: 'Anlagen',
        nav_impact: 'Auswirkungen',
        nav_vault: 'Tresor',
        dash_title: 'ESG-Dashboard',
        overview: 'Portfolio-Übersicht',
        carbon_seq: 'Kohlenstoff-Seq.',
        trees: 'Aktive Bäume',
        yield: 'C-Cred-Rendite',
        rwa_title: 'RWA-Sicherheit',
        ods_title: 'SDG-Ziele',
        verified_ok: 'AUDITOR_VERIFIED — Verifiziert durch Vereda Orakel',
        verified_pend: 'PENDING_AUDIT — Verifizierung ausstehend',
        tab_login: 'Login',
        tab_onboarding: 'Onboarding',
        tab_profile: 'Profil & RWA',
        tab_missions: 'Missionen',
        profile_title: 'Unternehmensprofil',
        btn_buy_trees: 'Bäume Kaufen (RWA)',
        mission_title: 'Kampagnen & Missionen',
        leafs_avail: 'Verfügbare LEAFs',
        locked_missions: 'Gesperrte Missionen',
        locked_desc: 'Kaufen Sie RWA-Bäume, um LEAF-Token freizuschalten und Kampagnen zu erstellen.',
        create_mission: 'Neue Mission',
        miss_name: 'Name der Kampagne',
        miss_desc: 'Regeln',
        miss_reward: 'Belohnung (LEAFs)',
        btn_launch: 'Kampagne Starten',
        buy_sim_loading: 'Warten auf RWA-Abwicklung...',
        login_title: 'Institutioneller Login',
        login_desc: 'Greifen Sie auf Ihr Dashboard bei Stellar zu.',
        login_doc: 'Firmen-E-Mail oder ID',
        login_pwd: 'Passwort',
        btn_login: 'Anmelden',
        btn_freighter: 'Freighter Verbinden (Web3)',
        login_sim_msg: 'Authentifizierung bei Stellar...',
    },
    zh: {
        b2b_title: 'B2B 注册',
        b2b_desc: '在 Stellar 网络上配置您的 ESG 审计账本。',
        section_registry: '机构注册',
        label_nature: '业务性质',
        opt_pequena: '小型企业（本地零售）',
        opt_industria: '工业（制造）',
        opt_servicos: '服务（咨询、代理）',
        opt_servicos_digitais: '数字服务（SaaS、平台）',
        opt_empreendedor: '数字创业者（KOL、信息产品）',
        label_name: '公司名称 / 艺名',
        label_doc: '企业 ID / 税号',
        label_email: '联系邮箱',
        label_phone: '电话号码',
        btn_generate: '生成加密身份',
        provisioning: '正在配置...',
        prov_desc: '在 Stellar 上注册 SBT 和抵押品',
        success_badge: '✓ 账户已配置',
        wallet_label: 'Stellar 钱包',
        status_sbt: '企业 SBT ✓',
        status_lastro: '10 棵树苗抵押 ✓',
        infra_label: '基础设施：Etherfuse Direct',
        infra_desc: '法定资本转换为受监管的金库抵押品。',
        btn_fiat: '结算充值',
        nav_field: '现场',
        nav_assets: '资产',
        nav_impact: '影响',
        nav_vault: '金库',
        dash_title: 'ESG 仪表板',
        overview: '投资组合概览',
        carbon_seq: '碳封存',
        trees: '活跃树木',
        yield: 'C-Cred 收益率',
        rwa_title: 'RWA 抵押品',
        ods_title: 'SDG 目标',
        verified_ok: 'AUDITOR_VERIFIED — Vereda 预言机已验证',
        verified_pend: 'PENDING_AUDIT — 等待验证',
        tab_login: '登录',
        tab_onboarding: '登录',
        tab_profile: '资料与 RWA',
        tab_missions: '任务',
        profile_title: '公司简介',
        btn_buy_trees: '购买树木 (RWA)',
        mission_title: '活动与任务',
        leafs_avail: '可用 LEAF',
        locked_missions: '任务已锁定',
        locked_desc: '在您的个人资料中购买 RWA 树木以向协议注入流动性，解锁 LEAF 代币并创建参与活动。',
        create_mission: '创建新任务',
        miss_name: '活动名称',
        miss_desc: '规则',
        miss_reward: '奖励 (LEAFs)',
        btn_launch: '启动活动',
        buy_sim_loading: '等待 RWA 结算...',
        login_title: '机构登录',
        login_desc: '访问您在 Stellar 网络上的企业仪表板。',
        login_doc: '工作邮箱 或 企业ID',
        login_pwd: '密码',
        btn_login: '登入',
        btn_freighter: '连接 Freighter 钱包 (Web3)',
        login_sim_msg: '正在身份验证...',
    },
    ja: {
        b2b_title: 'B2B オンボーディング',
        b2b_desc: 'StellarネットワークにESG監査台帳をプロビジョニングします。',
        section_registry: '法人登録',
        label_nature: '事業の性質',
        opt_pequena: '中小企業（地元小売業）',
        opt_industria: '産業（製造業）',
        opt_servicos: 'サービス（コンサルティング、代理店）',
        opt_servicos_digitais: 'デジタルサービス（SaaS、プラットフォーム）',
        opt_empreendedor: 'デジタル起業家（インフルエンサー）',
        label_name: '会社名 / 芸名',
        label_doc: '企業ID / マイナンバー',
        label_email: '連絡先メールアドレス',
        label_phone: '電話番号',
        btn_generate: '暗号IDを生成する',
        provisioning: 'プロビジョニング中...',
        prov_desc: 'StellarにSBTと担保を登録しています',
        success_badge: '✓ アカウントプロビジョニング完了',
        wallet_label: 'Stellarウォレット',
        status_sbt: '企業SBT ✓',
        status_lastro: '10本の苗木担保 ✓',
        infra_label: 'インフラ：Etherfuse Direct',
        infra_desc: '法定通貨資本を規制された金庫の担保に変換します。',
        btn_fiat: '法定通貨の寄付を決済する',
        nav_field: 'フィールド',
        nav_assets: '資産',
        nav_impact: '影響',
        nav_vault: '金庫',
        dash_title: 'ESGダッシュボード',
        overview: 'ポートフォリオ概要',
        carbon_seq: '炭素隔離',
        trees: 'アクティブな木',
        yield: 'C-Cred 利回り',
        rwa_title: 'RWA 担保',
        ods_title: 'SDG 目標',
        verified_ok: 'AUDITOR_VERIFIED — Vereda オラクルによる検証済み',
        verified_pend: 'PENDING_AUDIT — 検証待ち',
        tab_login: 'ログイン',
        tab_onboarding: 'オンボーディング',
        tab_profile: 'プロファイル & RWA',
        tab_missions: 'ミッション',
        profile_title: '会社概要',
        btn_buy_trees: '木を購入 (RWA)',
        mission_title: 'キャンペーンとミッション',
        leafs_avail: '利用可能な LEAF',
        locked_missions: 'ロックされたミッション',
        locked_desc: 'RWAの木を購入してLEAFトークンのロックを解除し、ミッションを作成します。',
        create_mission: '新しいミッション',
        miss_name: 'キャンペーン名',
        miss_desc: 'ルール',
        miss_reward: '報酬 (LEAFs)',
        btn_launch: 'キャンペーン開始',
        buy_sim_loading: 'RWA決済待ち...',
        login_title: '法人ログイン',
        login_desc: 'Stellarネットワークのダッシュボードにアクセスします。',
        login_doc: 'メールアドレス または 企業ID',
        login_pwd: 'パスワード',
        btn_login: 'サインイン',
        btn_freighter: 'Freighter 接続 (Web3)',
        login_sim_msg: 'Stellarで認証中...',
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('pt');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
